# =============================================
# ISC-DHCP-SERVER – 6 VLANs SIO.LAN (2025)
# =============================================

# =============================================
# DDNS Config
# =============================================

include "/etc/dhcp/rndc.key";
ddns-update-style interim;
ddns-domainname "sio.lan";
ddns-rev-domainname "in-addr.arpa";
update-static-leases on;
zone sio.lan. { primary 127.0.0.1; key rndc-key; }
zone 10.168.192.in-addr.arpa. { primary 127.0.0.1; key rndc-key; }
zone 20.168.192.in-addr.arpa. { primary 127.0.0.1; key rndc-key; }
zone 30.168.192.in-addr.arpa. { primary 127.0.0.1; key rndc-key; }
zone 40.168.192.in-addr.arpa. { primary 127.0.0.1; key rndc-key; }
zone 50.168.192.in-addr.arpa. { primary 127.0.0.1; key rndc-key; }
zone 60.168.192.in-addr.arpa. { primary 127.0.0.1; key rndc-key; }


# Global settings

default-lease-time 86400;
max-lease-time 172800;
authoritative;

option domain-name "sio.lan";
option domain-name-servers 192.168.10.2;

# group "Serveurs" {
#     host siodhcp  { hardware ethernet 08:00:27:c3:fa:15; fixed-address 192.168.10.2; }
#     host siodns   { hardware ethernet 08:00:27:bc:fa:ad; fixed-address 192.168.10.3; }
#     host siotftp  { hardware ethernet 08:00:27:5e:e5:68; fixed-address 192.168.10.4; }
#     host siopsi   { hardware ethernet 08:00:27:f9:c0:65; fixed-address 192.168.10.5; }
# }

# =============================================
# VLAN 10 – 192.168.10.0/24
# =============================================
subnet 192.168.10.0 netmask 255.255.255.0 {
	range 192.168.10.100 192.168.10.200;
	option routers 192.168.10.2;
	option broadcast-address 192.168.10.255;

#============= Host test !
	host criss { hardware ethernet e8:9c:25:7f:fc:81; fixed-address 192.168.10.10; }	# A005 / Asus TUF 16 Advantage / Cristian
}

# =============================================
# VLAN 20 – 192.168.20.0/24
# =============================================
subnet 192.168.20.0 netmask 255.255.255.0 {
    range 192.168.20.100 192.168.20.200;
    option routers 192.168.20.1;
    option broadcast-address 192.168.20.255;
}

# =============================================
# VLAN 30 – 192.168.30.0/24
# =============================================
subnet 192.168.30.0 netmask 255.255.255.0 {

# General setting for subnet

#	range 192.168.30.100 192.168.30.200;
	option routers 192.168.30.1;
	option broadcast-address 192.168.30.255;

# ========================== Host Admins
    host sioa10 { hardware ethernet b8:85:84:ae:e2:d9; fixed-address 192.168.30.10; }   # A005 / Dell Optiplex 7060 / Sio : 2024-2026
    host sioa11 { hardware ethernet b8:85:84:ae:e6:54; fixed-address 192.168.30.11; }   # A005 / Dell Optiplex 7060 / Sio : 2024-2026
    host sioa12 { hardware ethernet b8:85:84:ae:e6:1c; fixed-address 192.168.30.12; }   # A005 / Dell Optiplex 7060 / Sio : 2024-2026
    host sioa13 { hardware ethernet b8:85:84:ae:e5:83; fixed-address 192.168.30.13; }   # A005 / Dell Optiplex 7060 / Sio : 2024-2026
    host sioa14 { hardware ethernet b8:85:b4:ae:e5:f0; fixed-address 192.168.30.14; }   # A005 / Dell Optiplex 7060 / Sio : 2024-2026
    host sioa15 { hardware ethernet b8:85:84:ae:e8:d4; fixed-address 192.168.30.15; }   # A005 / Dell Optiplex 7060 / Sio : 2024-2026
# ================= Libre de 192.168.30.16 à 192.168.30.244 ============

}

# VLAN 40
subnet 192.168.40.0 netmask 255.255.255.0 {
    range 192.168.40.100 192.168.40.200;
    option routers 192.168.40.1;
}

# VLAN 50
subnet 192.168.50.0 netmask 255.255.255.0 {
    range 192.168.50.100 192.168.50.200;
    option routers 192.168.50.1;
}

# VLAN 60
subnet 192.168.60.0 netmask 255.255.255.0 {
    range 192.168.60.100 192.168.60.200;
    option routers 192.168.60.1;
}
